FROM alpine:3.19

# Install ca-certificates to connect to Google APIs over HTTPS and tzdata for dates
RUN apk update && apk add --no-cache ca-certificates tzdata

WORKDIR /app

# Copy the pre-compiled binary from the local bin directory
COPY ./bin/pulse /app/pulse

# Expose default HTTP port
EXPOSE 8080

# Run the stateless binary
CMD ["/app/pulse"]
